id: I81DB819B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T01:02:51+00:00'
last_modified: '2022-06-15T18:24:56.243377+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4942
  title: འདས་པའི་ལོ་ཟླ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    9BAD:
      image_group_id: I3CN8655
      title: Volume 1 of 'das pa'i lo zla/
      total_pages: 328
      order: 1
      base_file: 9BAD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
